### ISSUE TITLE
Bug: Not logging searches to CIF

### ISSUE THREAD

**Issue by aflick2486** [csirtgadgets/cif-chrome#19]
When you search using the plugin, it does not log the search in CIF. We have a fork of the plugin internally that uses an older version. The only difference is between the cif.js files. If it is helpful, we can share with you our cif.js file to try and figure out the issue.

**Comment by coonsmatthew** [comment]
We also verified that it was not an API key/access issue as we used several different API keys as well as using the keys to run manual CIF queries on the CIF server, which were logged. We do have the "log queries"  check box checked on the extension.

**Comment by coonsmatthew** [comment]
@wesyoung Hey, I wanted to check if you had any ideas on what may be causing searches using the plugin to not be logged.
