### ISSUE TITLE
Uppercase hash search does not work

### ISSUE THREAD

**Issue by coonsmatthew** [csirtgadgets/cif-chrome#20]
Hello, 

It seems that hashes (md5/sha1/sha256) are normalized to modify any upper case letters to lower case. 

If a hash includes upper case letters when it is added using the Chrome plugin, it is automatically normalized in the backend CIF database to a hash with lower case letters. 

However, if a user tries to search for the same hash based indicator using the chrome plugin with upper case letters, the search will not normalize the hash to lower case characters and will not return any results.

**Comment by wesyoung** [comment]
fixed in 2.0.10. be through the webstore in ~60m
