### ISSUE TITLE
Search UI table is not present

### ISSUE THREAD

**Issue by coonsmatthew** [csirtgadgets/cif-chrome#22]
It seems after a recent update to Chrome, the CIF search table is collapsed, almost like Chrome does not support tables in a plugin any more. 

I tried to re-download the plugin to make sure it wasn't anything I was doing wrong. 

![screen shot 2017-12-22 at 7 52 03 am](https://user-images.githubusercontent.com/8397734/34298693-08f0ebda-e6ed-11e7-9549-90c1469a70a8.png)

**Comment by wesyoung** [comment]
i'm assuming you're doing this against v2? do you have a screenshot of something with actual results? or do the results not come back either?

**Comment by coonsmatthew** [comment]
Results do come back. It's weird, it's almost like Chrome changed some setting that strips the table that the Plugin creates or something. 

Here's my chrome version: 
Google Chrome is up to date
Version 63.0.3239.108 (Official Build) (64-bit)

Screenshot below. 
![screen shot 2018-01-03 at 9 44 09 am](https://user-images.githubusercontent.com/8397734/34524821-e2ed624c-f06a-11e7-9fbe-7df2ca1d2a79.png)

**Comment by coonsmatthew** [comment]
We've also got an internal fork of the "official" plugin, and it stopped displaying the table results at the same time as well.

**Comment by wesyoung** [comment]
ack- taking a look at.. doesn't surprise me, i've seen google moving chrome into a more restrictive direction lately so prob something simple..

**Comment by wesyoung** [comment]
ok, try what's in master- chrome getting a little more restrictive about css and js, had to tweak it a bit... let me know and i'll pub it.

**Comment by coonsmatthew** [comment]
Yep, I just loaded the extension and it works! I think it's good to publish. 

Thank you.
